services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: estoque
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: /bin/sh -c "sleep 20 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma:/app/data

volumes:
  uptime-kuma:
